---
- hosts: all
  sudo: true
  tasks:
    - name: Configure epel repo
      yum: name=http://dl.fedoraproject.org/pub/epel/7/x86_64/e/epel-release-7-5.noarch.rpm state=present
    - name: Install binaries
      yum: name={{ item }} state=latest
      with_items:
        - vim
        - httpd
        - mariadb-server
        - php
        - php-pdo
        - php-mysql
        - php-pecl-geoip
        - php-pecl-apcu
        - GeoIP
        - wget
    - name: Download waffle
      get_url: url=http://waf-fle.org/downloads/waf-fle_0.6.4.tar.gz dest=/tmp
    - name: Uncompress waffle
      command: /bin/tar -xzf /tmp/waf-fle_0.6.4.tar.gz --directory=/usr/local
    - name: Link to the app directory
      file: src=/usr/local/waf-fle_0.6.4 dest=/usr/local/waf-fle state=link
    - name: Copy waffle apache configuration
      copy: src=waf-fle.conf dest=/etc/httpd/conf.d/waf-fle.conf 
    - name: Copy waffle configuration
      copy: src=config.php.waffle dest=/usr/local/waf-fle/config.php
    - name: Start services
      service: name={{ item }} state=started
      with_items:
        - httpd
        - mariadb
    - name: Stop firewall
      service: name=firewalld state=stopped
    - name: Set mysql root password
      command: /usr/bin/mysqladmin -u root password 'waffle'
