---
- hosts: all
  sudo: true
  tasks:
    - name: Install binaries
      yum: name={{ item }} state=latest
      with_items:
        - vim
        - httpd
        - mysql-server
        - php
        - php-pdo
        - php-mysql
        - php-pecl-apc
        - php-pecl-geoip
        - GeoIP
        - wget
    - name: Creates GeoIPISP.dat
      command: /bin/cp /usr/share/GeoIP/GeoIPASNum.dat /usr/share/GeoIP/GeoIPISP.dat creates=/usr/share/GeoIP/GeoIPISP.dat
    - name: Download waffle
      get_url: url=http://waf-fle.org/downloads/waf-fle_0.6.4.tar.gz dest=/tmp
    - name: Uncompress waffle
      command: /bin/tar -xzf /tmp/waf-fle_0.6.4.tar.gz --directory=/usr/local
    - name: Link to the app directory
      file: src=/usr/local/waf-fle_0.6.4 dest=/usr/local/waf-fle state=link
    - name: Copy waffle apache configuration
      copy: src=waf-fle.conf dest=/etc/httpd/conf.d/waf-fle.conf 
    - name: Copy waffle configuration
      copy: src=config.php.waffle dest=/usr/local/waf-fle/config.php
    - name: Start services
      service: name={{ item }} state=started
      with_items:
        - httpd
        - mysqld
    - name: Set mysql password 1
      command: /usr/bin/mysqladmin -u root password 'waffle'
